from contextlib import AbstractContextManager
from typing import Any

from httpx import Response

class TestClient(AbstractContextManager["TestClient"]):
    app: Any

    def __init__(self, app: Any, base_url: str = ...) -> None: ...
    def __enter__(self) -> TestClient: ...
    def __exit__(self, *args: object) -> None: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
