#!/usr/bin/env python3
"""Dump FastAPI's derived OpenAPI schema to YAML.

The committed file is a snapshot of ``app.openapi()``, not an authored spec.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
HEADER = "# Generated by `make openapi`. Do not edit.\n"


def export(path: Path) -> None:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    from app.main import app

    dumped = yaml.dump(
        app.openapi(),
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )
    path.write_text(HEADER + dumped, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "openapi.yaml",
        help="Destination YAML path",
    )
    args = parser.parse_args()
    export(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
